image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2
  COMPOSER_CACHE_DIR: /root/.composer/cache
  NPM_CONFIG_CACHE: /root/.npm

before_script:
  - echo "ENV_STAGE VARIABLE"
  - cp -f $ENV_STAGE ./.env

docker-build:
  stage: build
  script:
    - docker-compose up -d --build
    - docker-compose exec -T php composer install
    - docker-compose exec -T php php artisan key:generate
    - docker-compose exec -T php php artisan config:clear
    - docker-compose exec -T php php artisan cache:clear
    - docker-compose exec -T php php artisan config:cache
    - docker-compose exec -T php php artisan jwt:secret
    - docker-compose exec -T node npm install
    - docker-compose exec -T node npm run build
  artifacts:
    expire_in: 1 month
    paths:
      - vendor/
      - node_modules/
      - public/css/
      - public/js/
      - .env
  rules:
    - if: $CI_COMMIT_TAG =~ /^stage-.*$/

codestyle:
  stage: test
  script:
    - docker-compose exec -T php composer lint
  dependencies:
    - docker-build
  rules:
    - if: $CI_COMMIT_TAG =~ /^stage-.*$/

analyse:
  stage: test
  script:
    - docker-compose exec -T php composer analyse
  dependencies:
    - docker-build
  rules:
    - if: $CI_COMMIT_TAG =~ /^stage-.*$/

phpunit:
  stage: test
  script:
    - docker-compose exec -T php php artisan test
  dependencies:
    - docker-build
  rules:
    - if: $CI_COMMIT_TAG =~ /^stage-.*$/

deploy:
  stage: deploy
  script:
    - echo "Deploying to FTP server"
    - curl -T "path/to/local/file" "ftp://$FTP_SERVER/path/to/remote/file" --user "$FTP_USERNAME:$FTP_PASSWORD"
  rules:
    - if: $CI_COMMIT_TAG =~ /^stage-.*$/
