FROM php:8.1-cli

RUN apt-get update && apt-get install -y \
    cron \
    libpq-dev \
    libjpeg-dev \
    libpng-dev \
    libfreetype6-dev \
    libzip-dev \
    zip \
    unzip \
    && docker-php-ext-install pdo_mysql

COPY laravel-cron /etc/cron.d/laravel-cron

RUN chmod 0644 /etc/cron.d/laravel-cron

RUN crontab /etc/cron.d/laravel-cron

RUN touch /var/log/laravel_schedule.log

CMD ["sh", "-c", "cron && php /var/www/html/artisan queue:work --sleep=3 --tries=3 --timeout=90 >> /var/log/laravel_schedule.log 2>&1 && tail -f /var/log/laravel_schedule.log"]
